param([string]$Repository = (Split-Path $PSScriptRoot -Parent))
$ErrorActionPreference = 'Stop'
$board = Join-Path $Repository 'boards/micoair743v2_aio35'
$generated = (Resolve-Path (Join-Path $board 'generated/micoair743v2_aio35')).Path

# CubeMX 6.15 CLI can emit these intact files into a duplicated Windows path.
foreach ($entry in @(
    @('startup_stm32h743vihx.s', 'Core/Startup'),
    @('sysmem.c', 'Core/Src'),
    @('syscalls.c', 'Core/Src')
)) {
    $source = Get-ChildItem (Join-Path $generated 'STM32CubeIDE') -Recurse -File -Filter $entry[0] | Select-Object -First 1
    if ($source) {
        $destination = Join-Path $generated $entry[1]
        New-Item -ItemType Directory -Force $destination | Out-Null
        Copy-Item -LiteralPath $source.FullName -Destination $destination -Force
    }
    if (!(Test-Path (Join-Path (Join-Path $generated $entry[1]) $entry[0]))) {
        throw "Missing generated file: $($entry[0])"
    }
}

# Preserve the CubeMX implementation; only fill its regeneration-safe hooks.
$appPath = Join-Path $generated 'Core/Src/app_threadx.c'
$content = [IO.File]::ReadAllText($appPath)
$content = [regex]::Replace($content, '(?s)(/\* USER CODE BEGIN Includes \*/).*?(/\* USER CODE END Includes \*/)', '$1' + "`n#include `"app.h`"`n" + '$2')
$content = [regex]::Replace($content, '(?s)(/\* USER CODE BEGIN App_ThreadX_Init \*/).*?(/\* USER CODE END App_ThreadX_Init \*/)', '$1' + "`n  (void)memory_ptr;`n  ret = app_start();`n  " + '$2')
[IO.File]::WriteAllText($appPath, $content)

# USBX only needs the generated startup thread and CDC activation callbacks.
$usbPath = Join-Path $generated 'USBX/App/app_usbx_device.c'
$content = [IO.File]::ReadAllText($usbPath)
$content = [regex]::Replace($content, '(?s)(/\* USER CODE BEGIN Includes \*/).*?(/\* USER CODE END Includes \*/)', '$1' + "`n#include `"main.h`"`n#include `"ux_dcd_stm32.h`"`nextern PCD_HandleTypeDef hpcd_USB_OTG_FS;`n" + '$2')
$usbStart = @'
  TX_PARAMETER_NOT_USED(thread_input);
  HAL_PCDEx_SetRxFiFo(&hpcd_USB_OTG_FS, 128);
  HAL_PCDEx_SetTxFiFo(&hpcd_USB_OTG_FS, 0, 64);
  HAL_PCDEx_SetTxFiFo(&hpcd_USB_OTG_FS, 1, 64);
  HAL_PCDEx_SetTxFiFo(&hpcd_USB_OTG_FS, 2, 16);
  if (ux_dcd_stm32_initialize((ULONG)USB_OTG_FS, (ULONG)&hpcd_USB_OTG_FS) != UX_SUCCESS)
    Error_Handler();
  if (HAL_PCD_Start(&hpcd_USB_OTG_FS) != HAL_OK) Error_Handler();
'@
$content = [regex]::Replace($content, '(?s)(/\* USER CODE BEGIN app_ux_device_thread_entry \*/).*?(/\* USER CODE END app_ux_device_thread_entry \*/)', '$1' + "`n$usbStart`n  " + '$2')
[IO.File]::WriteAllText($usbPath, $content)

$cdcPath = Join-Path $generated 'USBX/App/ux_device_cdc_acm.c'
$content = [IO.File]::ReadAllText($cdcPath)
$content = [regex]::Replace($content, '(?s)(/\* USER CODE BEGIN Includes \*/).*?(/\* USER CODE END Includes \*/)', '$1' + "`n#include `"usb_log.h`"`n" + '$2')
$content = [regex]::Replace($content, '(?s)(/\* USER CODE BEGIN USBD_CDC_ACM_Activate \*/).*?(/\* USER CODE END USBD_CDC_ACM_Activate \*/)', '$1' + "`n  usb_log_attach(cdc_acm_instance);`n  " + '$2')
$content = [regex]::Replace($content, '(?s)(/\* USER CODE BEGIN USBD_CDC_ACM_Deactivate \*/).*?(/\* USER CODE END USBD_CDC_ACM_Deactivate \*/)', '$1' + "`n  (void)cdc_acm_instance;`n  usb_log_attach(UX_NULL);`n  " + '$2')
[IO.File]::WriteAllText($cdcPath, $content)

$iocPath = Join-Path $generated 'micoair743v2_aio35.ioc'
$content = [IO.File]::ReadAllText($iocPath)
$content = [regex]::Replace($content, '(?m)^ProjectManager.CustomerFirmwarePackage=.*', 'ProjectManager.CustomerFirmwarePackage=')
$content = [regex]::Replace($content, '(?m)^ProjectManager.DefaultFWLocation=.*', 'ProjectManager.DefaultFWLocation=true')
$content = [regex]::Replace($content, '(?m)^ProjectManager.LastFirmware=.*', 'ProjectManager.LastFirmware=false')
[IO.File]::WriteAllText($iocPath, $content)

# Freeze the actual vendored source list. No source discovery at build time.
$threadx = Join-Path $generated 'Middlewares/ST/threadx'
$sources = @(
    Get-ChildItem (Join-Path $threadx 'common/src') -File -Filter '*.c'
    Get-ChildItem (Join-Path $threadx 'ports/cortex_m7/gnu/src') -File -Filter '*.S'
) | Sort-Object FullName
$lines = @('# ThreadX 6.4.0 from X-CUBE-AZRTOS-H7 3.4.0; generated by tools/normalize-board.ps1.', 'set(THREADX_SOURCES')
foreach ($source in $sources) {
    $relative = $source.FullName.Substring($threadx.Length + 1).Replace('\', '/')
    $lines += '    "${TX}/' + $relative + '"'
}
$lines += ')'
[IO.File]::WriteAllLines((Join-Path $board 'threadx-sources.cmake'), $lines)

$usbx = Join-Path $generated 'Middlewares/ST/usbx'
$usbSources = Get-ChildItem $usbx -Recurse -File -Filter '*.c' | Sort-Object FullName
$lines = @('# USBX 6.4.0 device CDC ACM; generated by tools/normalize-board.ps1.', 'set(USBX_SOURCES')
foreach ($source in $usbSources) {
    $relative = $source.FullName.Substring($usbx.Length + 1).Replace('\', '/')
    $lines += '    "${UX}/' + $relative + '"'
}
$lines += ')'
[IO.File]::WriteAllLines((Join-Path $board 'usbx-sources.cmake'), $lines)

# Remove only obsolete output from this task's earlier generator attempts.
$obsolete = @('Src', 'Inc', 'cmake', 'CMakeLists.txt', 'CMakePresets.json', 'startup_stm32h743xx.s', 'STM32H743XX_FLASH.ld')
$obsolete += @(Get-ChildItem (Join-Path $generated 'STM32CubeIDE') -Directory | ForEach-Object { 'STM32CubeIDE/' + $_.Name })
foreach ($relative in $obsolete) {
    $candidate = Join-Path $generated $relative
    if (Test-Path -LiteralPath $candidate) {
        $resolved = (Resolve-Path -LiteralPath $candidate).Path
        if (!$resolved.StartsWith($generated + '\', [StringComparison]::OrdinalIgnoreCase)) {
            throw "Cleanup escaped generated directory: $resolved"
        }
        Remove-Item -LiteralPath $resolved -Recurse -Force
    }
}
Write-Output "Normalized real CubeMX output; $($sources.Count) ThreadX sources."
